import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { apiClient } from "../libs/apiClient";

const Home: NextPage = () => {
  const [data, setData] = useState();

  const get = async () => {
    const { data } = await apiClient.get("devices");
    console.log({ data });
    setData(data);
  };

  return (
    <div>
      <Head>
        <title>SwitchBot Controller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={get}>click</button>
      <div>{data}</div>
    </div>
  );
};

export default Home;
